networks:
  default:
    external:
      name: roboshop

services:
  mongodb:
    image: mongodb:1
    container_name: mongodb

  catalogue:
    image: catalogue:1
    container_name: catalogue
    depends_on:
      - mongodb

  web:
    image: web:1
    container_name: web
    depends_on:
    - catalogue
    - cart
    - user
    - shipping
    - payment

  